name: Deploy Backend to Render

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # This ensures the workflow only runs when files in backend directory change
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ../../  # Navigate back to root since GitHub Actions checks out the whole repo
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'
          
      - name: Install dependencies
        working-directory: backend
        run: npm ci
        
      - name: Run linting
        working-directory: backend
        run: npm run lint
        
      - name: Build project
        working-directory: backend
        run: npm run build
        
      - name: Deploy to Render
        working-directory: backend
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" 